apiVersion: batch/v1
kind: Job
metadata:
  name: seed-todo-db
  namespace: todo-app
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: seed-db
        image: postgres:16
        command: [ "sh", "-c" ]
        args:
            - |
              psql "host=$POSTGRES_HOST user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB" <<EOF
              INSERT INTO "Todos" (title, completed, "createdAt", "updatedAt") VALUES
              ('Learn K8s', false, now(), now()),
              ('Setup Ingress', true, now(), now()),
              ('Deploy API', false, now(), now()),
              ('Configure Postgres PVC', true, now(), now()),
              ('Test Rolling Update', false, now(), now());
              EOF
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
